services:
  postgres-db:
    image: postgres:15-alpine
    container_name: fisioterapia-sql
    environment:
      POSTGRES_DB: fisio_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=test --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  mongodb:
    image: mongo:latest
    container_name: fisioterapia-nosql
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password_secret
      MONGO_INITDB_DATABASE: fisio_logs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: "mongostat -n 1"
      interval: 5s
      timeout: 2s
      retries: 60

  volumes:
    postgres_data:
    mongo_data: