services:
  postgres-db:
    image: postgres:15-alpine
    container_name: fisioterapia-sql
    environment:
      POSTGRES_DB: fisio_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_secret
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    container_name: fisioterapia-nosql
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password_secret
      MONGO_INITDB_DATABASE: fisio_logs
    ports:
      - "27017:27017"