name: pulls.yml
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      TESTCONTAINERS_RYUK_DISABLED: "true"
      TESTCONTAINERS_CHECKS_DISABLE: "true"
      DOCKER_HOST: "unix:///var/run/docker.sock"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Docker
        run: |
            echo "=== DOCKER VERSION ==="
            docker --version
            echo "=== DOCKER INFO ==="
            docker info
            echo "=== SOCKET PERMISSIONS ==="
            ls -la /var/run/docker.sock
            echo "=== TESTING DOCKER HELLO WORLD ==="
            docker run --rm hello-world

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Run Tests
        run: mvn -f backend/Fisioterapia_TFG/pom.xml clean verify

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: '**/target/site/jacoco/'